#!/bin/sh

echo 116 > /sys/class/gpio/export
echo 112 > /sys/class/gpio/export
echo 20 > /sys/class/gpio/export
echo 16 > /sys/class/gpio/export
echo 17 > /sys/class/gpio/export
echo 18 > /sys/class/gpio/export
echo 41 > /sys/class/gpio/export
echo 42 > /sys/class/gpio/export
echo 21 > /sys/class/gpio/export
echo 19 > /sys/class/gpio/export
echo 1 > /sys/class/gpio/export
echo 9 > /sys/class/gpio/export
echo 3 > /sys/class/gpio/export
echo 40 > /sys/class/gpio/export
echo 150 > /sys/class/gpio/export
echo 162 > /sys/class/gpio/export
echo 160 > /sys/class/gpio/export
echo 161 > /sys/class/gpio/export
echo 158 > /sys/class/gpio/export
echo 159 > /sys/class/gpio/export
echo 92 > /sys/class/gpio/export
echo 85 > /sys/class/gpio/export
echo 123 > /sys/class/gpio/export
echo 124 > /sys/class/gpio/export
echo 125 > /sys/class/gpio/export
echo 126 > /sys/class/gpio/export
echo 127 > /sys/class/gpio/export
echo 133 > /sys/class/gpio/export
echo 134 > /sys/class/gpio/export
echo 135 > /sys/class/gpio/export
echo 136 > /sys/class/gpio/export
echo 137 > /sys/class/gpio/export
echo 138 > /sys/class/gpio/export
echo 139 > /sys/class/gpio/export
echo 140 > /sys/class/gpio/export
echo 141 > /sys/class/gpio/export
echo 142 > /sys/class/gpio/export
echo 143 > /sys/class/gpio/export
echo 54 > /sys/class/gpio/export
echo 205 > /sys/class/gpio/export
echo 32 > /sys/class/gpio/export
echo 35 > /sys/class/gpio/export
echo 34 > /sys/class/gpio/export
echo 33 > /sys/class/gpio/export
echo 101 > /sys/class/gpio/export
echo 144 > /sys/class/gpio/export
echo 145 > /sys/class/gpio/export
echo 89 > /sys/class/gpio/export
echo 105 > /sys/class/gpio/export
echo 104 > /sys/class/gpio/export
echo 57 > /sys/class/gpio/export
echo 56 > /sys/class/gpio/export
echo 55 > /sys/class/gpio/export
echo 88 > /sys/class/gpio/export

chmod -R 777 /sys/class/gpio/* 
